### ISSUE TITLE
How about a DLL?

### ISSUE THREAD

**Issue by WindowsNT** [sotanakamura/winui3-without-midl#1]
Excellent, it works. I am about to replace my old approach (https://www.codeproject.com/Articles/5359576/WinUI3-in-Existing-Win32-Applications) with this one.

Question: Can I make a DLL instead? I 'm trying to but since (I assume) it calls GetModuleHandle(0) which means the handle of my EXE instead of the DLL is taken, it doesn't work.

Great work.

**Comment by sotanakamura** [comment]
I think the easiest way is to create Windows Runtime components as .winmd and .dll. So what you need to do is defining the classes in MIDL, generate stubs and implement them , and then generate header files with cppwinrt tool. See https://learn.microsoft.com/en-us/windows/uwp/winrt-components/create-a-windows-runtime-component-in-cppwinrt

**Comment by sotanakamura** [comment]
By the way, it is written in standard C++, so you may be able to create a DLL in normal way. Make sure that you call `init_apartment` and `Application::start` to instantiate Application class in context of calling the DLL. Please try it!

**Comment by sotanakamura** [comment]
If you want to call the DLL from existing Win32 app, it is recommended to use xaml islands for WinUI 3 which is being developed now.
