### ISSUE TITLE
Fails to compile with latest 1.3 App SDK

### ISSUE THREAD

**Issue by HolgerStrauss** [sotanakamura/winui3-without-midl#2]
Thank you for providing this example code.
Unfortunately, when updating the WindowsAppSDK from 1.2.221109.1 to the latest stable 1.3 (1.3.23050200), it does not compile any more. There seems to be some issue with the Xaml compiler.
Do you have any idea how to fix this?

**Comment by sotanakamura** [comment]
I can not reproduce the bug. I used the latest Visual Studio 2022 and WinAppSDK. Please clone the repo, update all nuget packages, and then build it. If you still have a problem please give me more info.

**Comment by HolgerStrauss** [comment]
My mistake. I have only updated the WindowsAppSDK package. After updating the other packages to the latest versions, it works. Many thanks for looking into this.
